require('config.lazy')
require('config.keymaps')
require('config.lsp')
require('config.completions')
require('config.nvim-treesitter')
require('config.nvim-dap')
require('config.options')
require('config.snippets')
